name: Release

on:
  release:
    types:
      - created
      
env:
  DOCKER_IMAGE: 'wollac/ledger-bolos'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Get release version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/tags/}
        
    - name: Build Nano S
      run: |
        docker run -u $(id -u):$(id -g) -v $(pwd):/project -e BOLOS_SDK=/project/dev/sdk/nanos-secure-sdk $DOCKER_IMAGE make -C /project
        zip -j nanos-app-${{ env.RELEASE_VERSION }}.zip bin/app.hex LICENSE README.md
        rm -fr obj bin debug dep src/glyphs.c src/glyphs.h
        
    - name: Build Blue
      run: |
        docker run -u $(id -u):$(id -g) -v $(pwd):/project -e BOLOS_SDK=/project/dev/sdk/blue-secure-sdk $DOCKER_IMAGE make -C /project
        zip -j blue-app-${{ env.RELEASE_VERSION }}.zip bin/app.hex LICENSE README.md
        rm -fr obj bin debug dep src/glyphs.c src/glyphs.h

    - name: Upload Nano S
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./nanos-app-${{ env.RELEASE_VERSION }}.zip
        asset_name: nanos-app-${{ env.RELEASE_VERSION }}.zip
        asset_content_type: application/zip
        
    - name: Upload Blue
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./blue-app-${{ env.RELEASE_VERSION }}.zip
        asset_name: blue-app-${{ env.RELEASE_VERSION }}.zip
        asset_content_type: application/zip
